prefix = "."
stop-words = "stopwords.txt"

dataset = "cranfield"
corpus = "line.toml"
index = "idx"

query-judgements = "test_results.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "current_query.txt"
query-id-start = 1
